Registration action cycle
nirgn975/InsurancePensionHackathon pull request #22
Opened 2017-11-02 07:19 UTC by DavidBronfen

Fix 15

2017-11-02 14:13 UTC, nirgn975 requested changes

2017-11-02 14:13 UTC, nirgn975 commented on client/src/app/registration/registration.component.html
> +      <input matInput formcontrolname="password" (keyup)=checkError($event) placeholder="סיסמה"type="password">
`formcontrolname` => `formControlName`

2017-11-05 07:29 UTC, DavidBronfen commented
@nirgn975 Last thing I still need to do here is the password-confirm password validation, let's discuss it before I start work on it.

2017-11-06 06:44 UTC, nirgn975 approved these changes
LGTM

2017-11-06 06:47 UTC, merged